services:
  - type: web
    name: youtube-splitter
    env: node
    plan: standard
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FFMPEG_PATH
        value: /usr/bin/ffmpeg
      - key: FFPROBE_PATH
        value: /usr/bin/ffprobe
      - key: YOUTUBE_API_KEY
        sync: false
    disk:
      name: downloads
      mountPath: /opt/render/project/src/downloads
      sizeGB: 1
    resources:
      memory: 1GB
      cpu: 1
    autoDeploy: true 