services:
  - type: web
    name: youtube-splitter
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: downloads
      mountPath: /opt/render/project/src/downloads
      sizeGB: 1 